/**
 * Prekey store (Phase 1) — persists the responder's signed ML-KEM prekey pool and implements the
 * handshake's ResponderInviteStore. One-time prekeys are consumed DURABLY (fsync before return) so a
 * crash can't resurrect a consumed prekey → no PQ-FS regression (gate C-2). Encrypt-at-rest via
 * secure-fs; a single last-resort covers availability.
 *
 * Path/identity injected (no electron import) so it's testable with a temp dir + vault disabled.
 */
import { secureReadText, secureWriteFile } from '../storage/secure-fs';
import {
  generateKemPrekey, encodeKemPrekey, decodeKemPrekey, type IdentityKeyPair, type KemPrekey,
  type KemPrekeyKeyPair
} from './identity';
import { randomBytes } from './crypto';

const TOKEN_LEN = 32;
const DEFAULT_POOL = 20;

interface StoredPrekey {
  pid: string;       // hex prekeyId
  enc: string;       // base64 encodeKemPrekey(prekey)
  sk: string;        // base64 ML-KEM secret
  token: string | null; // base64 one-time token (first-contact invites) or null
}
/** Per-contact issuance record: the most-recent pid is pinned in `current`; older ones age out of
 * `recent[]` (FIFO, oldest at index 0) once it exceeds RECENT_CAP. Bounded per contact, so churn on
 * one contact can never evict another contact's index (rev-4 goal 7). */
interface IssuedEntry {
  current: string;   // hex pid of this contact's most-recent issuance (always pinned)
  recent: string[];  // older hex pids, oldest-first, bounded to RECENT_CAP
}
interface PrekeyFile {
  v: number;         // schema/parameter version — bump invalidates stale (wrong-size) prekeys
  oneTime: StoredPrekey[];
  lastResort: StoredPrekey | null;
  /** Per-contact issuance index (cid → {current, recent[]}). Survives consume() (only the secret is
   * deleted). Bounded as #contacts × (1 + RECENT_CAP); no global cap, no cross-contact eviction. */
  issued: Record<string, IssuedEntry>;
  /** Derived reverse index pid-hex → cid for O(1) identifyContact. Kept consistent with `issued` on
   * every mutation; rebuilt from `issued` if absent/malformed on read. */
  pidToCid: Record<string, string>;
}
// v4 = ML-KEM-1024 prekeys + per-contact issuance index (rev-4 goal 7). A file at an older version is
// discarded on read (old 768-sized prekeys can't decode; the rev-1 flat `issued` map is a different
// shape) and regenerated by ensurePool — fine for an off-by-default beta with the v4 suite bump.
const PREKEY_FILE_VERSION = 4;

const b64 = (u: Uint8Array): string => Buffer.from(u).toString('base64');
const unb64 = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'base64'));
const hex = (u: Uint8Array): string => Buffer.from(u).toString('hex');

/** Anchors how many recent ids per contact the index retains (spec open-q #4). NOTE: as of #40 this no
 * longer gates offerCurrent (the in-store mint-cap throw was removed in favor of re-offer-first; the
 * mint-churn bound now lives in the per-dial reject cap + the Task 2.5 rate-limiter). It survives ONLY
 * as the source for the RECENT_CAP coupling (Task 1.1-R): the index must retain at least this many
 * recent ids per contact so every outstanding prekey stays attributable; hence RECENT_CAP >= MINT_CAP,
 * asserted at module load below. */
export const MINT_CAP = 4;
/** How many older pids (beyond `current`) the per-contact index keeps. Source of truth; the test
 * imports this. Bounded per contact ⇒ no cross-contact eviction (the rev-1 global-cap defect). */
export const RECENT_CAP = MINT_CAP;
// Coupling invariant: if recent[] held fewer than MINT_CAP ids, an outstanding (issued-but-unconsumed)
// prekey could fall off the index and lose its contact attribution. Fail loud at load if violated.
if (RECENT_CAP < MINT_CAP) {
  throw new Error(`prekey-store invariant: RECENT_CAP (${RECENT_CAP}) must be >= MINT_CAP (${MINT_CAP})`);
}

const isPlainObject = (x: unknown): x is Record<string, unknown> =>
  typeof x === 'object' && x !== null && !Array.isArray(x);

/** Coerce a persisted `issued` field to the per-cid shape, dropping anything malformed (e.g. a rev-1
 * flat pid→cid string map, where each value is a string not a {current,recent} object). Tolerant by
 * design: an unrecognized/old shape yields an empty index (start fresh) rather than throwing. */
function sanitizeIssued(raw: unknown): Record<string, IssuedEntry> {
  if (!isPlainObject(raw)) return {};
  const out: Record<string, IssuedEntry> = {};
  for (const [cid, v] of Object.entries(raw)) {
    if (!isPlainObject(v)) continue; // rev-1 string value, or junk → skip this entry
    const current = typeof v.current === 'string' ? v.current : '';
    const recent = Array.isArray(v.recent) ? v.recent.filter((p): p is string => typeof p === 'string') : [];
    if (!current && recent.length === 0) continue;
    out[cid] = { current, recent: recent.slice(-RECENT_CAP) };
  }
  return out;
}

/** Deterministically rebuild the pid→cid reverse index from `issued`: for each contact, map `current`
 * and every `recent` pid back to its cid. Object/array iteration order is the on-disk order. */
function rebuildPidToCid(issued: Record<string, IssuedEntry>): Record<string, string> {
  const rev: Record<string, string> = {};
  for (const [cid, entry] of Object.entries(issued)) {
    for (const p of entry.recent) rev[p] = cid;
    if (entry.current) rev[entry.current] = cid; // within this cid, current overwrites any recent entry for the same pid
  }
  return rev;
}

/** Record an issuance of `pid` to `cid` in the per-contact index, demoting the prior `current` into
 * `recent[]`, trimming `recent[]` to RECENT_CAP, and keeping the reverse `pidToCid` index consistent
 * (deleting the reverse entry of any pid that ages off `recent[]`). Mutates `f` in place. */
function recordIssued(f: PrekeyFile, cid: string, pid: string): void {
  const entry = f.issued[cid] ?? { current: '', recent: [] };
  if (entry.current && entry.current !== pid) entry.recent.push(entry.current); // demote old current
  entry.current = pid;
  // The demoted pid may already be in recent[] (re-issue); de-dup so the cap reflects distinct ids.
  entry.recent = entry.recent.filter((p, i) => p !== pid && entry.recent.indexOf(p) === i);
  while (entry.recent.length > RECENT_CAP) {
    const dropped = entry.recent.shift()!; // oldest-first eviction within this contact only
    if (f.pidToCid[dropped] === cid) delete f.pidToCid[dropped]; // age the reverse index too
  }
  f.issued[cid] = entry;
  f.pidToCid[pid] = cid;
}
export class PrekeyStore {
  private chain: Promise<unknown> = Promise.resolve();
  // One-time prekeyIds currently in-flight in a handshake. Closes a lookup→consume TOCTOU under the
  // engine's concurrent inbound dispatch: without it, two streams replaying the same one-time prekeyId
  // both pass lookup before either consumes, serving one "one-time" prekey to two sessions (a PQ-FS /
  // replay regression, gate C-2). In-memory (per process) — consumption durability is unchanged.
  private readonly reserved = new Set<string>();

  constructor(private readonly file: string, private readonly identity: IdentityKeyPair) {}

  private serialize<T>(fn: () => Promise<T>): Promise<T> {
    const run = this.chain.then(fn, fn);
    this.chain = run.catch(() => undefined);
    return run;
  }

  private async read(): Promise<PrekeyFile> {
    const empty = (): PrekeyFile => ({ v: PREKEY_FILE_VERSION, oneTime: [], lastResort: null, issued: {}, pidToCid: {} });
    try {
      const p = JSON.parse(await secureReadText(this.file)) as Partial<PrekeyFile>;
      // Discard a stale-parameter pool (e.g. ML-KEM-768 prekeys from before the 1024 swap, or the rev-1
      // flat `issued` map): they can't decode / are the wrong shape. The version gate means an old-format
      // file never reaches the per-cid coercion below — it returns fresh — so old files can't crash us.
      if (p.v !== PREKEY_FILE_VERSION) return empty();
      const issued = sanitizeIssued(p.issued);
      return {
        v: PREKEY_FILE_VERSION,
        oneTime: Array.isArray(p.oneTime) ? p.oneTime : [],
        lastResort: p.lastResort ?? null,
        issued,
        // Never trust the persisted reverse index: ALWAYS rebuild it from `issued` (current first, then
        // recent oldest-first). The rebuild is one cheap linear pass over already-sanitized data and is
        // guaranteed consistent with `issued`, closing the type-safety gap where a corrupted file could
        // smuggle non-string values past the isPlainObject guard.
        pidToCid: rebuildPidToCid(issued),
      };
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return empty();
      throw err;
    }
  }

  private async write(f: PrekeyFile): Promise<void> {
    // durable: consumption/issuance state must survive a crash (gate C-2)
    await secureWriteFile(this.file, JSON.stringify(f), { durable: true });
  }

  private async mint(token: Uint8Array | null, isLastResort = false): Promise<StoredPrekey> {
    const { prekey, secretKey } = await generateKemPrekey(this.identity, isLastResort);
    return { pid: hex(prekey.prekeyId), enc: b64(encodeKemPrekey(prekey)), sk: b64(secretKey), token: token ? b64(token) : null };
  }

  private hydrate(s: StoredPrekey): { prekey: KemPrekey; secretKey: Uint8Array; token: Uint8Array | null } {
    return { prekey: decodeKemPrekey(unb64(s.enc)), secretKey: unb64(s.sk), token: s.token ? unb64(s.token) : null };
  }

  /** Ensure a last-resort prekey exists + the one-time pool is topped up to `size`. */
  ensurePool(size = DEFAULT_POOL): Promise<void> {
    return this.serialize(async () => {
      const f = await this.read();
      if (!f.lastResort) f.lastResort = await this.mint(null, true);
      while (f.oneTime.length < size) f.oneTime.push(await this.mint(null));
      await this.write(f);
    });
  }

  /** Mint a first-contact invite: a fresh one-time prekey bound to a fresh token. */
  issueFirstContactInvite(): Promise<{ prekey: KemPrekey; token: Uint8Array }> {
    return this.serialize(async () => {
      const f = await this.read();
      const token = randomBytes(TOKEN_LEN);
      const s = await this.mint(token);
      f.oneTime.push(s);
      await this.write(f);
      return { prekey: decodeKemPrekey(unb64(s.enc)), token };
    });
  }

  // ---- ResponderInviteStore ----
  // Reserve-on-lookup (inside the serialized chain): a one-time prekey is atomically marked in-flight, so a
  // concurrent handshake replaying the same prekeyId gets null. The reservation is released on abort
  // (release) or finalized on success (consume). Last-resort is reusable, so it is never reserved.
  lookup(prekeyId: Uint8Array): Promise<{ prekey: KemPrekey; secretKey: Uint8Array; token: Uint8Array | null } | null> {
    return this.serialize(async () => {
      const f = await this.read();
      const id = hex(prekeyId);
      const oneTime = f.oneTime.find((x) => x.pid === id);
      if (oneTime) {
        if (this.reserved.has(id)) return null; // already in-flight in another handshake — fail closed
        this.reserved.add(id);
        return this.hydrate(oneTime);
      }
      if (f.lastResort?.pid === id) return this.hydrate(f.lastResort);
      return null;
    });
  }

  /** Release a reservation taken by lookup() when the handshake aborts before consuming the prekey. */
  release(prekeyId: Uint8Array): Promise<void> {
    return this.serialize(async () => { this.reserved.delete(hex(prekeyId)); });
  }

  consume(prekeyId: Uint8Array): Promise<void> {
    return this.serialize(async () => {
      const f = await this.read();
      const id = hex(prekeyId);
      this.reserved.delete(id);
      if (f.lastResort?.pid === id) return; // last-resort is reused — never consumed
      const before = f.oneTime.length;
      f.oneTime = f.oneTime.filter((x) => x.pid !== id);
      if (f.oneTime.length !== before) await this.write(f); // durable delete
    });
  }

  issueNext(cid?: string): Promise<KemPrekey> {
    return this.serialize(async () => {
      const f = await this.read();
      const s = await this.mint(null);
      f.oneTime.push(s);
      if (cid !== undefined) recordIssued(f, cid, s.pid);
      await this.write(f);
      return decodeKemPrekey(unb64(s.enc));
    });
  }

  /** Whether a given prekeyId is the stored LAST-RESORT prekey (signed, reusable, FS-degraded). Cheap
   *  index check — no crypto, no reservation. The responder reconnect pre-gate (Task 2.5 / N-3) uses it
   *  to reject a reconnect Msg1 that carries a last-resort prekey_id BEFORE any asymmetric work. */
  isLastResortId(prekeyId: Uint8Array): Promise<boolean> {
    return this.serialize(async () => {
      const f = await this.read();
      return f.lastResort?.pid === hex(prekeyId);
    });
  }

  /** Look up which contact was issued a given prekeyId. Returns null if unknown. Survives consume(). */
  identifyContact(prekeyId: Uint8Array): Promise<string | null> {
    return this.serialize(async () => {
      const f = await this.read();
      return f.pidToCid[hex(prekeyId)] ?? null;
    });
  }

  /**
   * Offer a current prekey for a reconnect-recovery Reject (re-offer-FIRST, #40 / spec §2 fidelity).
   *
   * Re-offer FIRST, NEVER throw: return the contact's newest still-unconsumed already-issued prekey
   * (its `current`, else the newest `recent[]` whose secret is still in the pool). Re-offer neither
   * consumes nor changes the pool — `remaining()` is unchanged. A legitimate stranded peer that is
   * already holding several unconsumed prekeys MUST still be served its newest one (the old per-cid
   * "mint cap" throw refused exactly that peer — removed). Only when the contact has NO unconsumed
   * issued prekey at all is a fresh one-time prekey minted and indexed under cid.
   *
   * The mint-churn bound now lives elsewhere, not in this store: re-offer-first caps each cid to <=1
   * offerCurrent-minted outstanding prekey at a time (the next call re-offers it instead of minting
   * again); the per-dial responder reject cap (Task 2.4, MAX_REJECTS_PER_DIAL) bounds calls per dial;
   * the Task 2.5 reconnect rate-limiter bounds calls across dials.
   *
   * Last-resort (signed, isLastResort) is the floor only when the one-time pool is GLOBALLY exhausted.
   */
  offerCurrent(cid: string): Promise<KemPrekeyKeyPair> {
    return this.serialize(async () => {
      const f = await this.read();
      // Secret still in the pool ⇒ unconsumed (consume() deletes it from oneTime). O(1) membership.
      const live = new Set(f.oneTime.map((x) => x.pid));
      const entry = f.issued[cid];

      // Re-offer FIRST: newest unconsumed issued prekey — current first, then recent[] newest-first.
      // Never throws, never mints, never consumes — this is the spec §2 "first returns the newest
      // unconsumed" path and must serve even a peer already holding many outstanding prekeys.
      if (entry) {
        const ordered = entry.current ? [entry.current, ...[...entry.recent].reverse()] : [...entry.recent].reverse();
        for (const pid of ordered) {
          if (!live.has(pid)) continue;
          const s = f.oneTime.find((x) => x.pid === pid)!;
          return { prekey: decodeKemPrekey(unb64(s.enc)), secretKey: unb64(s.sk) }; // no mint, no consume, no write
        }
      }

      // None unconsumed → mint one, index it under cid. Last-resort only when the one-time pool is
      // globally exhausted (a fresh mint still lands in oneTime, so this is the floor).
      if (f.oneTime.length === 0 && f.lastResort) {
        return { prekey: decodeKemPrekey(unb64(f.lastResort.enc)), secretKey: unb64(f.lastResort.sk) };
      }
      const s = await this.mint(null);
      f.oneTime.push(s);
      recordIssued(f, cid, s.pid);
      await this.write(f);
      return { prekey: decodeKemPrekey(unb64(s.enc)), secretKey: unb64(s.sk) };
    });
  }

  /** Diagnostics: remaining one-time prekeys. */
  async remaining(): Promise<number> {
    return (await this.read()).oneTime.length;
  }
}
